### ISSUE TITLE
实体识别部分获取已有entity是否有问题？

### ISSUE THREAD

**Issue by ForgotLove** [panchunguang/ccks_baidu_entity_link#11]
我发现无论是BERT-ENE模型获取到的内容必定匹配到已有entity，而BERT-CRF序列标注模型即使获取到一个可能的实体之后，也会在ER_result.py进行融合的时候，因为没有对应的entity而直接被忽略，最后传入到实体链接的模型必定是已有entity的标准文本，这样做是否合理？
我举个例子，经过BERT-CRF模型之后，“什么是社保？”，取到"社保"这个实体。“什么是社保卡？”，取到“社保卡”这个实体。“什么是社保局？”，取到“社保局”这个实体。但是却都因为不在entity字典中而被舍去了，ER_result.py执行之后三句话的mention结果都是空，实际三者完全可以关联到"社会保障"的相关知识（实体）的。
做实体链接单纯考虑相同文本，或者全部别名都罗列的情况可能么，如果模型只是为了解决同文本内容不同含义的话，而不包含同义词等相关内容的话，实际应用上应该不是那么准确吧？

**Comment by excelsimon** [comment]
我也有同样得疑问，这个比赛好像解决的主要是知识图谱中有很多同名实体，看了一些方案也是只考虑识别到图谱中的实体后同名实体间的消歧。然而实际上会面临识别到的实体并不在知识图谱中的情况。
