### ISSUE TITLE
bert参数共享

### ISSUE THREAD

**Issue by BeerTai** [panchunguang/ccks_baidu_entity_link#15]
您好，您论文中不同的bert的参数是共享的吗？还是不同的bert有不同的参数

**Comment by panchunguang** [comment]
当时没有共享，可以尝试一下共享BERT层的参数，这样可能效果更好



在 2020-12-07 14:57:15，"BeerTai" <notifications@github.com> 写道：

您好，您论文中不同的bert的参数是共享的吗？还是不同的bert有不同的参数

**Comment by BeerTai** [comment]
谢谢～
